/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FORMULARIOS;


import conexionSQL.conexionSQL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author danie
 */
public class registrousuarios11 extends javax.swing.JFrame {

        conexionSQL cc=new conexionSQL();
        Connection con=cc.conexion();
        
    /**
     * Creates new form sistema
     */
    public registrousuarios11() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(getBackground());
        this.setTitle("Control de Usuarios");
        mostrardatos();
         /*initComponents();
        this.setLocationRelativeTo(null);
        
        */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtmaquina = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtserie = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtmodelo = new javax.swing.JTextField();
        btnuevo = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        btnactualizar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablainventario = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        txtbuscar = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        menuinicial = new javax.swing.JMenuItem();
        menuinventario = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 0));

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setText("Nombre");

        jLabel2.setText("Apellido Paterno");

        jLabel3.setText("Carrera");

        jLabel4.setText("Matricula");

        btnuevo.setText("Nuevo");
        btnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnuevoActionPerformed(evt);
            }
        });

        btneliminar.setText("Eliminar");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        btnguardar.setText("Guardar");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        btnactualizar.setText("Actualizar");
        btnactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarActionPerformed(evt);
            }
        });

        jLabel7.setText("Apellido Materno");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnuevo)
                        .addGap(28, 28, 28)
                        .addComponent(btnguardar)
                        .addGap(18, 18, 18)
                        .addComponent(btneliminar)
                        .addGap(18, 18, 18)
                        .addComponent(btnactualizar))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtserie))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtmaquina, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtmodelo, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtmaquina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtserie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtmodelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btneliminar)
                    .addComponent(btnguardar)
                    .addComponent(btnuevo)
                    .addComponent(btnactualizar))
                .addGap(27, 27, 27))
        );

        tablainventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablainventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablainventarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablainventario);

        jLabel6.setText("Busqueda");

        txtbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscarActionPerformed(evt);
            }
        });
        txtbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbuscarKeyReleased(evt);
            }
        });

        jMenu3.setText("Inicio");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        menuinicial.setText("Control Inicial");
        menuinicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuinicialActionPerformed(evt);
            }
        });
        jMenu3.add(menuinicial);

        menuinventario.setText("Control Inventario");
        menuinventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuinventarioActionPerformed(evt);
            }
        });
        jMenu3.add(menuinventario);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscarActionPerformed
        // TODO add your handling code here:
        
      
    }//GEN-LAST:event_txtbuscarActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        insertardatos();
        limpiarcajas();
        mostrardatos();
        
        
// TODO add your handling code here:
    }//GEN-LAST:event_btnguardarActionPerformed
    
    private void btnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnuevoActionPerformed
        limpiarcajas();
        
// TODO add your handling code here:
    }//GEN-LAST:event_btnuevoActionPerformed

    private void tablainventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablainventarioMouseClicked
        int filaseleccionada = tablainventario.rowAtPoint(evt.getPoint());
        
        
        txtmaquina.setText(tablainventario.getValueAt(filaseleccionada, 0).toString());
        txtserie.setText(tablainventario.getValueAt(filaseleccionada, 1).toString());
        txtmodelo.setText(tablainventario.getValueAt(filaseleccionada, 2).toString());
       
        
// TODO add your handling code here:
    }//GEN-LAST:event_tablainventarioMouseClicked

    private void btnactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarActionPerformed
        actualizardatos();
        limpiarcajas();
        mostrardatos();
        
// TODO add your handling code here:
    }//GEN-LAST:event_btnactualizarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        eliminaregistro();
        mostrardatos();
        limpiarcajas();
        
// TODO add your handling code here:
    }//GEN-LAST:event_btneliminarActionPerformed

    private void txtbuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyReleased
        filtrardatos(txtbuscar.getText());
        
        
// TODO add your handling code here:
    }//GEN-LAST:event_txtbuscarKeyReleased

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
                      
// TODO add your handling code here:
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void menuinventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuinventarioActionPerformed
                registroinventario form=new registroinventario();
                    form.setVisible(true);
                    this.dispose();
        
// TODO add your handling code here:
    }//GEN-LAST:event_menuinventarioActionPerformed

    private void menuinicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuinicialActionPerformed

            registroinicial form=new registroinicial();
                    form.setVisible(true);
                    this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_menuinicialActionPerformed
    public void filtrardatos(String valor) {
    
        String titulos[]={"n_maquina","n_serie","modelo"};
        String[]registros=new String[3];
        
        DefaultTableModel modelo=new DefaultTableModel(null, titulos);
        
        String SQL="select * from inventario where n_serie like '%"+valor+"%'";
        
        try {
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery(SQL);
            
            while (rs.next()){
                registros[0]=rs.getString("n_maquina");
                registros[1]=rs.getString("n_serie");
                registros[2]=rs.getString("modelo");
                
                
                modelo.addRow(registros);
            }
            
            tablainventario.setModel(modelo);
               }catch(Exception e){
                   JOptionPane.showMessageDialog(null, "Error al mostrar datos"+ e.getMessage());
        }
        
        
        
        
}
    public void mostrardatos() {
    
        String titulos[]={"N° Maquina","N° Serie","Modelo"};
        String[]registros=new String[3];
        
        DefaultTableModel modelo=new DefaultTableModel(null, titulos);
        
        String SQL="select * from inventario";
        
        try {
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery(SQL);
            
            while (rs.next()){
                registros[0]=rs.getString("n_maquina");
                registros[1]=rs.getString("n_serie");
                registros[2]=rs.getString("modelo");
               
                
                modelo.addRow(registros);
            }
            
            tablainventario.setModel(modelo);
               }catch(Exception e){
                   JOptionPane.showMessageDialog(null, "Error al mostrar datos"+ e.getMessage());
        }
        
        
        
        
}
    public void eliminaregistro(){
        
        int filaseleccionada = tablainventario.getSelectedRow();
        
        try {
            String SQL = "Delete from alumnos where matricula=" +tablainventario.getValueAt(filaseleccionada, 0);
            Statement st =con.createStatement();
            int n = st.executeUpdate(SQL);
            if (n>=0) {
                JOptionPane.showMessageDialog(null, "Registro Eliminado");
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Error de Registro" + e.getMessage());
        }
    }
    public void limpiarcajas(){
        txtmaquina.setText("");
        txtserie.setText("");
        txtmodelo.setText("");
       
    }
    public void insertardatos(){
        try {
            String SQL="insert into inventario (n_serie, n_maquina, modelo) values (?,?,?)";
            //String SQL1="insert into materias (carrera) values (?)";
            //PreparedStatement pst1=con.prepareStatement(SQL1);
            PreparedStatement pst=con.prepareStatement(SQL);
            pst.setString(1, txtmaquina.getText());
            pst.setString(2, txtserie.getText());
            pst.setString(3, txtmodelo.getText());
            
           // pst1.setString(3, txtcarrera.getText());
            pst.execute();
            //pst1.execute();
           
            JOptionPane.showMessageDialog(null, "Registro Exitoso");
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Error de Registro" + e.getMessage());
        }}
    public void actualizardatos(){
        try {
            String SQL= "update inventario set n_maquina=?, n_serie=?, modelo=? where n_serie=?";
            
            int filaseleccionado=tablainventario.getSelectedRow();
            String dao=(String)tablainventario.getValueAt(filaseleccionado, 0);
            
            
            PreparedStatement pst=con.prepareStatement(SQL);
            
            pst.setString(2, txtmaquina.getText()); //2,txtnombre
            pst.setString(1, txtserie.getText());//3, txtapellidopa
            pst.setString(3, txtmodelo.getText());//4,txtapellidoma
           
            
            pst.setString(4, dao);
            pst.execute();
            
            
            JOptionPane.showMessageDialog(null, "Registro Editado Exitoso");
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Error de Edicion" + e.getMessage());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registrousuarios11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registrousuarios11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registrousuarios11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registrousuarios11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registrousuarios11().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnactualizar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem menuinicial;
    private javax.swing.JMenuItem menuinventario;
    private javax.swing.JTable tablainventario;
    private javax.swing.JTextField txtbuscar;
    private javax.swing.JTextField txtmaquina;
    private javax.swing.JTextField txtmodelo;
    private javax.swing.JTextField txtserie;
    // End of variables declaration//GEN-END:variables
}
